import { X } from "lucide-react";
import { Button } from "@/components/Button";

interface TermsAndConditionsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const SECTIONS = [
  {
    heading: null,
    body: `These Terms and Conditions ("Terms") constitute a legally binding agreement between you ("User", "you", "your") and AgriAxis International Ltd ("AgriAxis", "Company", "we", "our", or "us") governing your access to and use of the AgriAxis mobile application, web platform, APIs, dashboards, websites, artificial intelligence services, satellite analytics, digital tools, software, and all related services (collectively referred to as the "Platform").`,
  },
  {
    heading: null,
    body: `These Terms apply to all users including but not limited to: Individual Farmers, Farmer Groups, Cooperatives, Commercial Farms, Agribusinesses, Agricultural Consultants, Financial Institutions, Insurance Companies, Government Agencies, NGOs, Research Institutions, and Technology Partners.`,
  },
  {
    heading: "1. Definitions",
    items: [
      `User means any person or organization using the Platform.`,
      `Content means all text, reports, images, maps, dashboards, AI outputs, recommendations, software and documentation.`,
      `Services means every service provided by AgriAxis.`,
    ],
  },
  {
    heading: "2. Eligibility",
    body: "You confirm that:",
    items: [
      "You are at least eighteen (18) years old or legally authorized to enter into contracts.",
      "Information supplied during registration is accurate.",
      "You will keep your information current.",
      "If representing an organization, you have authority to bind that organization.",
    ],
  },
  {
    heading: "3. Services",
    body: "AgriAxis provides AI-powered agricultural intelligence using satellite imagery, machine learning and geospatial technologies. Services include:",
    items: [
      "Soil Health Intelligence", "Soil Fertility Interpretation", "Crop Monitoring",
      "Vegetation Index Monitoring", "Crop Health Assessment", "Pest Detection",
      "Disease Detection", "Climate Information", "Weather Advisory",
      "Climate Risk Analysis", "Crop Calendar", "Yield Estimation",
      "Farm Mapping", "Institutional Monitoring", "Enterprise Portfolio Management",
      "Carbon Monitoring", "Digital MRV", "AI Advisory Services", "Agricultural Analytics",
    ],
    footer: "Services may evolve over time. AgriAxis reserves the right to add, remove or modify services without prior notice.",
  },
  {
    heading: "4. Nature of Platform Outputs",
    body: "All outputs generated by AgriAxis are decision-support information only. They are not:",
    items: [
      "Laboratory soil tests", "Engineering reports", "Legal advice", "Insurance advice",
      "Financial advice", "Investment advice", "Regulatory certifications",
    ],
    footer: "Users remain solely responsible for all agricultural, commercial and financial decisions.",
  },
  {
    heading: "5. Artificial Intelligence",
    body: "The Platform uses Artificial Intelligence and predictive analytics. Users acknowledge that:",
    items: [
      "AI produces probabilistic estimates.",
      "Outputs may improve as additional data becomes available.",
      "AI recommendations should be supplemented with professional judgement where appropriate.",
      "AI may occasionally generate inaccurate or incomplete outputs.",
      "AgriAxis continuously improves AI models but does not guarantee perfection.",
    ],
  },
  {
    heading: "6. Satellite Data Disclaimer",
    body: "The Platform relies on satellite imagery and remote sensing technologies. Outputs may be affected by:",
    items: [
      "Cloud cover", "Atmospheric interference", "Satellite revisit intervals",
      "Image resolution", "Sensor limitations", "Terrain", "Vegetation density", "Seasonal conditions",
    ],
    footer: "AgriAxis therefore cannot guarantee absolute accuracy.",
  },
  {
    heading: "7. Agricultural Disclaimer",
    body: "Agriculture is inherently uncertain. Crop performance depends on factors beyond AgriAxis' control including: weather, rainfall, flooding, drought, pest outbreaks, diseases, soil variability, farmer practices, input quality, market conditions, government policy, and natural disasters. Accordingly, AgriAxis does not guarantee:",
    items: [
      "Crop yield", "Farm profitability", "Production targets", "Financial returns",
      "Insurance approval", "Lending approval", "Project success",
    ],
  },
  {
    heading: "8. User Responsibilities",
    body: "You agree to: use the Platform lawfully, provide accurate information, keep your credentials confidential, obtain necessary permissions before uploading third-party data, respect intellectual property rights, and comply with all applicable laws. You shall not:",
    items: [
      "Reverse engineer software.", "Copy proprietary algorithms.", "Scrape Platform data.",
      "Introduce malware.", "Attempt unauthorized access.", "Disrupt Platform operations.",
      "Use the Platform for unlawful purposes.",
    ],
  },
  {
    heading: "9. Privacy & Data Protection",
    body: "AgriAxis is committed to protecting personal information using internationally recognized privacy principles. The Platform is designed to align with applicable legislation including the Nigeria Data Protection Act (NDPA), NDPR, GDPR, UK GDPR, Kenya Data Protection Act, POPIA, CCPA, and other applicable national privacy laws. AgriAxis follows principles of transparency, accountability, lawfulness, purpose limitation, data minimization, integrity, confidentiality, security, and user rights.",
  },
  {
    heading: "10. Information We Collect",
    body: "Information may include:",
    items: [
      "Name", "Email", "Phone Number", "GPS Coordinates", "Farm Boundaries",
      "Crop Information", "Soil Information", "Device Information", "Browser Information",
      "Payment Information", "Usage Analytics", "Uploaded Images", "Uploaded Documents", "AI Interactions",
    ],
  },
  {
    heading: "11. How Information is Used",
    body: "Information may be used to:",
    items: [
      "Deliver Platform services", "Improve AI", "Generate reports", "Provide customer support",
      "Improve products", "Prevent fraud", "Secure the Platform",
      "Conduct research using anonymized data", "Meet regulatory obligations",
    ],
  },
  {
    heading: "12. Data Sharing",
    body: "AgriAxis never sells personal information. Information may only be shared with:",
    items: [
      "Cloud providers", "Payment processors", "Approved technology partners",
      "Research institutions using anonymized information", "Government authorities where legally required",
    ],
  },
  {
    heading: "13. International Data Transfers",
    body: "Information may be stored or processed outside your country. Where transfers occur, AgriAxis implements appropriate safeguards consistent with international standards.",
  },
  {
    heading: "14. User Rights",
    body: "Subject to applicable law you may request:",
    items: [
      "Access", "Correction", "Deletion", "Portability",
      "Restriction", "Withdrawal of Consent", "Objection to Processing",
    ],
  },
  {
    heading: "15. Intellectual Property",
    body: "All software, AI models, algorithms, databases, maps, reports, trademarks, logos, APIs, dashboards, designs and documentation remain the exclusive property of AgriAxis. Users receive only a limited, revocable, non-transferable licence to use the Platform.",
  },
  {
    heading: "16. Payments",
    body: "Paid services shall be governed by applicable pricing plans. Unless required by law: payments are non-refundable, prices may change upon notice, and failure to pay may result in suspension.",
  },
  {
    heading: "17. Third-Party Services",
    body: "AgriAxis integrates third-party services. We are not responsible for failures originating from satellite providers, weather providers, payment providers, cloud providers, or mapping services.",
  },
  {
    heading: "18. Service Availability",
    body: "Although AgriAxis targets enterprise-grade availability, uninterrupted operation cannot be guaranteed.",
  },
  {
    heading: "19. Limitation of Liability",
    body: "To the maximum extent permitted by law, AgriAxis shall not be liable for: crop losses, reduced yields, financial losses, lost profits, business interruption, insurance decisions, lending decisions, project delays, data loss, indirect damages, or consequential damages. Where liability cannot legally be excluded, total liability shall not exceed the total amount paid by the user during the preceding twelve (12) months.",
  },
  {
    heading: "20. Indemnity",
    body: "Users agree to indemnify and hold harmless AgriAxis, its directors, officers, employees, partners, affiliates, licensors, and contractors from claims arising from: misuse of the Platform, violation of these Terms, violation of applicable laws, or infringement of third-party rights.",
  },
  {
    heading: "21. Suspension and Termination",
    body: "AgriAxis may suspend or terminate access where users: breach these Terms, engage in fraud, compromise security, violate applicable laws, or abuse the Platform.",
  },
  {
    heading: "22. Force Majeure",
    body: "AgriAxis shall not be liable for delays or failures arising from events beyond its reasonable control, including natural disasters, satellite outages, internet failures, power interruptions, civil unrest, war, epidemics, governmental actions, or failures of third-party infrastructure.",
  },
  {
    heading: "23. Governing Law",
    body: "These Terms shall be governed by the laws of the Federal Republic of Nigeria, subject to mandatory consumer protection and data protection laws applicable in the jurisdiction where the user resides or operates.",
  },
  {
    heading: "24. Amendments",
    body: "AgriAxis may update these Terms periodically. Material updates will be communicated through the Platform or via registered email. Continued use constitutes acceptance of revised Terms.",
  },
  {
    heading: "25. Contact Information",
    body: null,
    contact: {
      company: "AgriAxis International Ltd",
      website: "www.agriaxis.org",
      email: "info@agriaxis.org",
      phone: "+2348114789104",
    },
  },
];

export const TermsAndConditionsModal: React.FC<TermsAndConditionsModalProps> = ({
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="relative flex h-[90vh] w-full max-w-2xl flex-col rounded-3xl bg-white shadow-2xl">
        {/* Header */}
        <div className="flex shrink-0 items-start justify-between border-b border-[#E8E8E8] px-8 py-6">
          <div>
            <h2 className="font-neue text-xl font-bold text-[#130B30]">
              Terms & Conditions
            </h2>
            <p className="mt-0.5 text-sm text-[#615C74]">
              AgriAxis International Ltd — Effective Date: January 2026
            </p>
          </div>
          <button
            onClick={onClose}
            className="grid size-8 shrink-0 place-items-center rounded-full bg-[#F5F5F5] transition-colors hover:bg-[#E8E8E8]"
          >
            <X size={16} className="text-[#423C59]" />
          </button>
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto px-8 py-6">
          <div className="space-y-6 text-sm leading-relaxed text-[#615C74]">
            {SECTIONS.map((section, i) => (
              <div key={i}>
                {section.heading && (
                  <h3 className="mb-2 font-neue font-semibold text-[#130B30]">
                    {section.heading}
                  </h3>
                )}
                {section.body && <p className="mb-2">{section.body}</p>}
                {section.items && section.items.length > 0 && (
                  <ul className="ml-5 list-disc space-y-1">
                    {section.items.map((item, j) => (
                      <li key={j}>{item}</li>
                    ))}
                  </ul>
                )}
                {section.footer && (
                  <p className="mt-2">{section.footer}</p>
                )}
                {section.contact && (
                  <div className="mt-2 space-y-1 rounded-xl border border-[#E8E8E8] bg-[#F9FAF9] p-4">
                    <p className="font-medium text-[#130B30]">{section.contact.company}</p>
                    <p>Website: <span className="text-[#0A814A]">{section.contact.website}</span></p>
                    <p>Email: <span className="text-[#0A814A]">{section.contact.email}</span></p>
                    <p>Phone: {section.contact.phone}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="shrink-0 border-t border-[#E8E8E8] px-8 py-5">
          <Button variant="primary" onClick={onClose}>
            I Understand
          </Button>
        </div>
      </div>
    </div>
  );
};
